### ISSUE TITLE
Error in Count pairs with given sum.cpp file

### ISSUE THREAD

**Issue by Ekj0t** [wbhima/CodeforALL#50]
There is a error in line 6 of Count pairs with given sum.cpp file

**Comment by surajkeshari** [comment]
can u assign me this task .there is a error in code of Count pairs with given sum.cpp.

**Comment by wbhima** [comment]
ok do it ASAP

**Comment by surajkeshari** [comment]
ok i am going to start.

**Comment by surajkeshari** [comment]
> ok do it ASAP
I have solved the issue please merge it.
