### ISSUE TITLE
Error in 11Count-words-in-string.cpp file

### ISSUE THREAD

**Issue by wasup-yash** [wbhima/CodeforALL#96]
This program does not give the required output as mentioned in the file name and in file comment too which is 11 . 
so could you assign me this so i can solve this issue .

**Comment by surajkeshari** [comment]
please assign this issue to me .

**Comment by wbhima** [comment]
@surajkeshari  u can pull a request for another file.

**Comment by wasup-yash** [comment]
done

**Comment by wbhima** [comment]
ok
